# -*- coding: utf-8 -*-
"""WilliamMelvinSukamto_0371755.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QazzJTSJIrR63TA376_KUVLN44cymoHO

## **1. Import Required Libraries**

This section imports all necessary Python libraries used for deep learning, data handling, visualisation, and evaluation.


*   `tensorflow` is the main deep learning framework to build, train, fine tune, and evaluate the convolutional neural network.
*  `tensorflow_datasets` is used to load the colorectal histology dataset.
*   `numpy` used for numerical operations, array manipulation, and efficient handling of image data and labels
*   `matplotlib` is used to visualise training performance and confusion matrices.
*   `itertools` used to iterate through parameters or to help format data for the confusion matrix.
*   `tensorflow.keras.layers` provides essential building blocks such as convolutional layers, max pooling layers, batch normalisation, dropout, and dense layers.
*   `tensorflow.keras.models` used to define the structure of the network, typically via the sequential API or the functional API.
*    `sklearn.metrics.confusion_matrix` computes the confusion matrix to evaluate classification performance across all classes.
"""

# 1 Import libraries

import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np
import matplotlib.pyplot as plt
import itertools
from tensorflow import keras
from tensorflow.keras import layers, models
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.metrics import confusion_matrix, classification_report, f1_score

"""## **2. Load Colorectal Histology Dataset**
This section uses TensorFlow Datasets (TFDS) to download and prepare the medical imaging data. This dataset contains 5,000 images across 8 tissue types (adipose, background, debris, lymphoma, mucosa, muscle, stroma, tumor).
*   `(ds_all,), ds_info = tfds.load(...)` downloads and loads the "colorectal_histology" dataset. It returns the data as a TensorFlow Dataset object and a metadata object (ds_info) containing dataset details.
*   `class_names = ds_info.features["label"].names` extracts the human-readable names for the classes, such as "Tumor" or "Mucosa," to be used for visualization and reporting.
*   `for _, label in ds_all:` iterates through the entire dataset to inspect the label of every image.



"""

# 2 Load Colorectal Histology Dataset

# Load dataset from TensorFlow Datasets
(ds_all,), ds_info = tfds.load(
    "colorectal_histology",
    split=["train"],
    as_supervised=True,
    with_info=True
)

# Extract class names
num_classes = ds_info.features["label"].num_classes
class_names = ds_info.features["label"].names

#Print number of classes, class names, and number of images
print("Number of classes:", num_classes)
print("Class names:", class_names)
print("Number of Images: ", ds_info.splits["train"].num_examples)

# Calculate and print the distribution of images per class
class_counts = {}
for _, label in ds_all:
    label_name = class_names[label.numpy()]
    class_counts[label_name] = class_counts.get(label_name, 0) + 1

print("\nDistribution of images per class:")
for class_name, count in class_counts.items():
    print(f"  {class_name}: {count} images")

"""## **3. Train-Validation Split**
After loading the dataset, it must be divided into subsets to ensure that the model is trained on one portion of data and evaluated on completely unseen data to test its generalization.


*   `ds_full.shuffle(dataset_size, seed=42)` randomizes the order of the images. The seed=42 ensures that the shuffle is reproducible, meaning you will get the same "random" order every time you run the code.
*   `ds_all.take(train_size)` creates the Training Set (70%) by taking the first 3,500 images. This data is used to teach the model how to recognize patterns.
*   `ds_all.skip(train_size).take(val_size)` creates the Validation Set (15%) by skipping the training images and taking the next 750. This is used to fine-tune hyperparameters and prevent overfitting during the training process.
*  `ds_all.skip(train_size + val_size)` creates the Test Set (15%) by skipping both training and validation data. This is the final "exam" for the model to see how it performs on totally new images.









"""

# 3 Train–Validation Split

# Total dataset size
dataset_size = ds_info.splits["train"].num_examples

# Define split sizes
train_size = int(0.7 * dataset_size)
val_size = int(0.15 * dataset_size)
test_size = dataset_size - train_size - val_size

# Shuffle dataset before splitting
ds_full = ds_all.shuffle(dataset_size, seed=42)

# Create splits 70% Train, 15% Val, 15% Test
ds_train = ds_full.take(train_size)
ds_val = ds_full.skip(train_size).take(val_size)
ds_test = ds_full.skip(train_size + val_size)

# Print number of total images
print("Total images")
print(f"Train set      : {len(ds_train)}")
print(f"Validation set : {len(ds_val)}")
print(f"Test set       : {len(ds_test)}")
print(f"Overall        : {len(ds_train) + len(ds_val) + len(ds_test)}")

"""## **4. Image Preprocessing and Data Augmentation**
This section prepares the raw images for the neural network. Preprocessing ensures all data is in a uniform format, while augmentation helps the model generalize better by creating variations of the training data.


*   `preprocess(image, label)` custom function that prepares individual images.

    *   `tf.image.resize(..., (IMG_SIZE, IMG_SIZE))` standardizes all images to 160 × 160 pixels. This is necessary because neural networks require a fixed input shape.
    *   `image / 255.0` normalizes pixel values from the range [0, 255] to [0, 1]. This helps the model converge faster during training.
*   `map(preprocess, ...)` applies the preprocessing function to every image in the dataset across all CPU cores simultaneously using AUTOTUNE.
*   `batch(BATCH_SIZE)` groups images into sets of 32. Instead of looking at one image at a time, the model updates its weights based on the average error of the whole batch.
*   `prefetch(tf.data.AUTOTUNE)` allows the CPU to prepare the next batch of data while the GPU is still processing the current one. This eliminates data bottlenecks.
*   `data_augmentation` is to improve model generalisation and to artificially increase dataset variety. So the model can learn more vary features:
    *   `RandomFlip` flips images horizontally.
    *   `RandomRotation(0.15)` rotates images by up to 15%.
    *   `RandomZoom(0.1)` zooms in or out by up to 10%.
    *   `RandomTranslation` shifts the image slightly horizontally or vertically.
    *   `RandomContrast(0.1)` randomly adjusts the brightness contrast
"""

# 4 Image Preprocessing and Data Augmentation

IMG_SIZE = 160  # Resize all images to 160 by 160
BATCH_SIZE = 32 # Group images into 32 sets
AUTOTUNE = tf.data.AUTOTUNE

# Resize and rescale images
def preprocess(image, label):
    image = tf.image.resize(image, (IMG_SIZE, IMG_SIZE))
    image = image / 255.0     # Normalize pixel values into [0,1]
    return image, label

# Training dataset
ds_train = (
    ds_train
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .shuffle(1000)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

# Validation dataset
ds_val = (
    ds_val
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

# Test dataset
ds_test = (
    ds_test
    .map(preprocess, num_parallel_calls=tf.data.AUTOTUNE)
    .batch(BATCH_SIZE)
    .prefetch(tf.data.AUTOTUNE)
)

# Data Augmentation
data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.15),
    layers.RandomZoom(0.1),
    layers.RandomTranslation(0.1, 0.1),
    layers.RandomContrast(0.1),
    ])

"""## **5. Build the CNN Model**

Simple CNN model architecture details and purpose of each layer:
*   `Convolutional Layers (Conv2D)` extract spatial features from input images, such as edges, textures, and patterns. Details:
    *   Block 1: 32 filters, 3×3 kernel, ReLU activation.
    *   Block 2: 64 filters, 3×3 kernel, ReLU activation.
    *   Block 3: 128 filters, 3×3 kernel, ReLU activation.
    *   Activation: ReLU introduces non-linearity, allowing the model to learn complex features.
*   `Batch Normalization (BatchNormalization)` normalizes activations for each mini-batch, improving training stability and convergence. Placed after each convolutional layer to reduce internal covariate shift.
*   `Pooling Layers (MaxPooling2D)` reduce spatial dimensions (height × width) while retaining important features. Helps decrease computational cost and provides spatial invariance.
    *   Pool size: 2×2 for each block.
*   `Flatten Layer (Flatten)` converts the 3D feature maps into a 1D vector, preparing it for fully connected layers.
*   `Fully Connected Layers (Dense)` combines the extracted features to perform high-level reasoning and classification.
    *   First Dense Layer: 128 units with ReLU activation.
*   `Dropout Layer` 40% dropout to prevent overfitting by randomly disabling neurons during training.
*   `Output Layer (Dense)` number of units equals num_classes (8) with Softmax activation.
    *   Softmax Activation: Converts the output logits into class probabilities for multi-class classification. Ensures all probabilities sum to 1 and can be interpreted as confidence scores for each class.



















"""

# 5 Build the CNN Model

model = keras.Sequential([
    # Input layer
    layers.Input(shape=(IMG_SIZE, IMG_SIZE, 3)),

    # Convolution Block 1
    layers.Conv2D(32, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),
    layers.BatchNormalization(),

    # Convolution Block 2
    layers.Conv2D(64, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),
    layers.BatchNormalization(),

    # Convolution Block 3
    layers.Conv2D(128, (3, 3), activation="relu", padding="same"),
    layers.MaxPooling2D((2, 2)),
    layers.BatchNormalization(),

    layers.GlobalAveragePooling2D(),
    layers.Flatten(), # Flatten 3D feature maps to 1D vector

    # Dense Layer 1
    layers.Dense(128, activation="relu"), # Fully connected layer for high-level features
    layers.Dropout(0.4), # Dropout for regularization

    # Dense Layer 2 (Output)
    layers.Dense(num_classes, activation="softmax") # Output layer with probabilities
])

# Print model summary
model.summary()

"""## **6. Compile and Train the Model**
This section configures the learning process and executes the model training. The compilation step defines the "rules" for improvement, while the training loop handles the actual learning through iterative passes.

*   `model.compile(...)` prepares the model for training by specifying the mathematical strategies for optimization and evaluation.
    *   `optimizer=keras.optimizers.Adam` advanced optimization algorithm that automatically adjusts the learning rate ($1 \times 10^{-3}$) for each parameter to speed up convergence.
    *  `loss="sparse_categorical_crossentropy"` the objective function used for multi-class classification where labels are provided as integers. The model strives to minimize this value.


*   `early_stop` callbacks function used to prevent overfitting and save computational time.

*   `model.fit(...)` feeds the processed data through the network.

"""

# 6 Compile and Train the Model

# Compile the model
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

# Early stopping
early_stop = keras.callbacks.EarlyStopping(
    monitor="val_loss",   # Watch validation loss
    patience=3,           # Stop if no improvement for 3 epochs
    restore_best_weights=True   # Roll back to the best validation loss weights
)

# Train the model
EPOCHS=30
history_initial = model.fit(
    ds_train,
    validation_data=ds_val,
    epochs=EPOCHS,
    callbacks=[early_stop]
)

"""## **7. Fine Tuning**
Fine-tuning is a process of refining the model's weights to achieve higher precision. This is typically done after initial training to "nudge" the model toward a better local minimum without destroying the patterns it has already learned.
*   `optimizer=keras.optimizers.Adam(learning_rate=1e-4)` re-compiles the model with a significantly lower learning rate ($1 \times 10^{-4}$). A smaller learning rate is crucial during fine-tuning to prevent large weight updates that could cause the model to forget previous learning
*   List item



"""

# 7 Fine Tuning

#Give lower learning rate
model.compile(
    optimizer=keras.optimizers.Adam(learning_rate=1e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

fine_tune_epochs = 20
history_fine = model.fit(
    ds_train,
    validation_data=ds_val,
    epochs=fine_tune_epochs
)

"""## **8. Plot Training Curves (Initial Training and after Fine Tuning)**
This section visualizes the model's learning progress by combining the metrics from both the initial training and fine-tuning phases into a single graph.

*   `acc / val_acc / loss / val_loss` these lines concatenate the lists of metrics from history_initial and history_fine. This allows for a continuous view of how the model improved across both training stages.

*   `plt.subplot(1,2,1)` creates the first chart in a side-by-side layout, focusing on Accuracy. This shows how well the model learned to correctly identify tissue types over time.
*   `plt.subplot(1,2,2)` creates the second chart focusing on Loss. This shows how the "error" or "penalty" decreased as the model's predictions became more confident and accurate.
*   `plt.axvline(...)` draws a vertical dashed line at the point where the initial training ended and fine-tuning began. This helps in identifying if the lower learning rate during fine-tuning provided a noticeable boost in performance.
*  `plt.tight_layout()` automatically adjusts the padding between the two subplots to ensure labels and titles do not overlap, making the final visualization clean and readable.




"""

# 8 Plot Training Curves (Initial Traning and after Fine Tuning)

# Accuracy and loss extraction
acc = history_initial.history["accuracy"] + history_fine.history["accuracy"]
val_acc = history_initial.history["val_accuracy"] + history_fine.history["val_accuracy"]

loss = history_initial.history["loss"] + history_fine.history["loss"]
val_loss = history_initial.history["val_loss"] + history_fine.history["val_loss"]
# Epoch index creation
epochs = range(len(acc))

plt.figure(figsize=(12,4))

# Accuracy plot
plt.subplot(1,2,1)
plt.plot(epochs, acc, label="Training accuracy")
plt.plot(epochs, val_acc, label="Validation accuracy")
plt.axvline(len(history_initial.history["accuracy"]) - 1, linestyle="--", color="gray", label="Fine tuning starts") # Draws a vertical dashed line at the epoch
plt.legend()
plt.title("Accuracy (Initial Training + Fine Tuning)")

# Loss plot
plt.subplot(1,2,2)
plt.plot(epochs, loss, label="Training loss")
plt.plot(epochs, val_loss, label="Validation loss")
plt.axvline(len(history_initial.history["loss"]) - 1, linestyle="--", color="gray", label="Fine tuning starts") # Draws a vertical dashed line at the epoch
plt.legend()
plt.title("Loss (Initial Training + Fine Tuning)")

plt.tight_layout()
plt.show()

"""## **9. Evaluate on Test Set**
This final step assesses the model's true performance by testing it on a completely unseen portion of the dataset. This provides an unbiased estimate of how the model will perform in a real-world clinical or research setting.
*   `model.evaluate(ds_test)` processes the entire test dataset through the model and computes the final loss and accuracy. Unlike training, this step does not update weights or use dropout; it simply reports how well the "finalized" model generalizes to new data.
*   Generalization Check: by comparing the test accuracy to the training and validation accuracy, you can determine if the model has successfully learned general features rather than just memorizing the training images.



"""

# 9 Evaluate on Test Set

test_loss, test_acc = model.evaluate(ds_test)
print("Test accuracy:", test_acc)
print("Test loss:", test_loss)

# Collect all true labels and predicted labels for confusion matrix

y_true = []
y_pred = []

for images, labels in ds_test:
    preds = model.predict(images, verbose=0)
    y_true.extend(labels.numpy())
    y_pred.extend(np.argmax(preds, axis=1))

y_true = np.array(y_true)
y_pred = np.array(y_pred)

#F1 Score Calculation
macro_f1 = f1_score(y_true, y_pred, average='macro')
weighted_f1 = f1_score(y_true, y_pred, average='weighted')

# Print confusion matrix and classification report
cm = confusion_matrix(y_true, y_pred)
print("Macro F1:", macro_f1)
print("Weighted F1:", weighted_f1)
print("Classification report")
print(classification_report(y_true, y_pred, target_names=class_names))

"""## **10. Plot Confusion Matrix**
The confusion matrix is a specialized tool for evaluating the performance of a classification model. It provides a detailed breakdown of how many times each tissue category was correctly identified and where the model made specific errors.

*   `plot_confusion_matrix(cm)` custom function designed to visualize the raw numbers of a confusion matrix in an intuitive, color-coded grid.
*   Annotating Cell Values:
    *   `itertools.product` iterates through every cell in the grid to place the exact count of images.
    *   `thresh = cm.max() / 2.0` calculates a threshold to automatically switch text color between white and black, ensuring the numbers are visible against both light and dark backgrounds.
*  `plt.xlabel("Predicted label") / plt.ylabel("True label")` organizes the chart so you can see what the tissue actually was (True) versus what the AI thought it was (Predicted).


"""

# 10 Plot Confusion Matrix

def plot_confusion_matrix(cm):
    plt.figure(figsize=(8, 8))
    plt.imshow(cm, cmap=plt.cm.Blues)
    plt.title("Confusion matrix")
    plt.xticks(range(num_classes), class_names)
    plt.yticks(range(num_classes), class_names)

    #Annotating cell values
    thresh = cm.max() / 2.0
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(
            j, i, format(cm[i, j], "d"),
            horizontalalignment="center",
            color="white" if cm[i, j] > thresh else "black"
        )

    plt.tight_layout()
    plt.xlabel("Predicted label")
    plt.ylabel("True label")
    plt.show()

plot_confusion_matrix(cm)

"""## **11. Visualise Correctly and Incorrectly Classified Images**
This section performs a qualitative evaluation of the model by displaying specific examples from the test set. By comparing instances where the model succeeded versus where it failed, you can gain insights into the visual patterns the model has mastered and those it finds ambiguous.

*   Logic for Selection: the code iterates through the ds_test dataset and compares the true_l (ground truth) with the pred_l (model prediction). It collects the first three instances of each for comparison.
*   `tf.nn.softmax` converts the raw model outputs (logits) into a probability distribution. This allows the visualization to show the Prob (confidence score), indicating how sure the model was about its prediction.
*   Correctly Classified Examples: these serve as a baseline to confirm that the model correctly identifies the defining features of tissue types like Tumor or Stroma when they appear clearly.
*   Misclassified Examples: these images highlight the model's limitations. For example, if the model predicts "Muscle" for a "Stroma" image with a high probability score, it suggests a specific textural similarity that may require further data or model tuning to distinguish.


"""

# 11 Visualise Correctly and Incorrectly Classified Images

correct_images = []
correct_labels = []
correct_preds = []

incorrect_images = []
incorrect_labels = []
incorrect_preds = []
incorrect_probs = []

# Iterate once more over the test set
for images, labels in ds_test:
    preds = model.predict(images, verbose=0)
    prob = tf.nn.softmax(preds, axis=1).numpy()
    pred_labels = np.argmax(preds, axis=1)

# Selecting correct and incorrect predictions
    for img, true_l, pred_l, prob_vec in zip(images, labels.numpy(), pred_labels, prob):
        if true_l == pred_l and len(correct_images) < 3:
            correct_images.append(img.numpy())
            correct_labels.append(true_l)
            correct_preds.append(pred_l)
        elif true_l != pred_l and len(incorrect_images) < 3:
            incorrect_images.append(img.numpy())
            incorrect_labels.append(true_l)
            incorrect_preds.append(pred_l)
            incorrect_probs.append(prob_vec[pred_l])

        if len(correct_images) >= 3 and len(incorrect_images) >= 3:
            break
    if len(correct_images) >= 3 and len(incorrect_images) >= 3:
        break

# Plot the images
def show_examples(images, true_labels, pred_labels, probs=None, title=""):
    plt.figure(figsize=(9, 3))
    for i in range(len(images)):
        plt.subplot(1, len(images), i + 1)
        plt.imshow(images[i])
        plt.axis("off")
        if probs is None:
            plt.title(f"True: {class_names[true_labels[i]]}\nPred: {class_names[pred_labels[i]]}")
        else:
            plt.title(
                f"True: {class_names[true_labels[i]]}\nPred: {class_names[pred_labels[i]]}\nProb: {probs[i]:.2f}"
            )
    plt.suptitle(title, y=1.25)
    plt.show()

show_examples(correct_images, correct_labels, correct_preds, title="Correctly classified examples")
show_examples(incorrect_images, incorrect_labels, incorrect_preds, incorrect_probs, title="Misclassified examples")